name: ipay
description: A smart shopping application for seamless mobile checkout experience.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  
  # State Management
  provider: ^6.0.5
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Authentication
  google_sign_in: ^7.0.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  
  # Barcode Scanning
  mobile_scanner: ^3.4.1
  permission_handler: ^11.0.1
  
  # Payment
  razorpay_flutter: ^1.3.5
  
  # QR Code Generation
  qr_flutter: ^4.1.0
  
  # Image and Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  cloudinary_flutter: ^0.0.1
  
  # Utils
  intl: ^0.20.2
  
  # PDF Generation
  pdf: ^3.10.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
  pull_to_refresh: ^2.0.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts (can be added later)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"


