services:
  - type: web
    name: ipay-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: ipay-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MESSAGECENTRAL_CUSTOMER_ID
        sync: false
      - key: MESSAGECENTRAL_EMAIL
        sync: false
      - key: MESSAGECENTRAL_PASSWORD
        sync: false
      - key: MESSAGECENTRAL_SENDER_ID
        value: iPay
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

databases:
  - name: ipay-mongodb
    plan: free

